Repository mungtage/frontend, pull requests merged in 2022-10, with the labels that each got.

#5 Feature/#4 client 테스트용 배포
  package-lock.json
  package.json
  public/favicon.ico
  public/favicon.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/api/.gitkeep
  src/assets/Logo.svg
  src/components/Header.js
  src/components/Main.js
  src/hooks/.gitkeep
  src/pages/Home.js
  src/utils/.gitkeep
  yarn.lock
Labels: frontend

#7 Feature/#3 이미지 업로드 기능 구현 완료
  package.json
  src/components/ImageUpload.js
  src/components/LostPost.js
  yarn.lock
Labels: frontend, feature

#8 Feature/#6 매칭 결과 페이지 스켈레톤 구현
  package-lock.json
  src/components/Tabs.js
  src/components/resultTab/MatchResult.js
  src/components/resultTab/RenderList.js
  src/pages/Home.js
Labels: frontend, feature

#12 F/#11 매칭 결과페이지 분기처리
  .eslintrc.json
  package-lock.json
  src/App.js
  src/components/LostPost.js
  src/components/Tabs.js
  src/components/resultTab/NoPost.js
  src/components/resultTab/NoResult.js
  src/components/resultTab/ResultTab.js
  src/pages/Home.js
  yarn.lock
Labels: frontend, feature

#13 Feature/#10
  src/components/Header.js
  src/components/lostPostTab/ImageUpload.js
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
  src/pages/Home.js
Labels: frontend, feature

#18 Feature/#17 공고 상세 스켈레톤
  src/App.js
  src/components/lostPostTab/LostPost.js
  src/components/resultDetail/NoticeContent.js
  src/components/resultTab/NoPost.js
  src/components/resultTab/RenderList.js
  src/components/resultTab/ResultTab.js
  src/pages/ResultDetail.js
Labels: frontend, feature

#22 Feature/#14 소셜로그인 구현
  src/App.js
  src/components/AuthCallback.js
  src/components/Header.js
Labels: frontend, feature

#28 Bugfix/#27
  src/components/lostPostTab/ImageUpload.js
  src/components/lostPostTab/LostForm.js
Labels: bug, frontend

#29 Feature/#21 매칭 결과 api
  .gitignore
  src/App.js
  src/components/AuthCallback.js
  src/components/Header.js
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
  src/components/resultDetail/NoticeContent.js
  src/components/resultTab/MatchResult.js
  src/components/resultTab/NoPost.js
  src/components/resultTab/RenderList.js
  src/components/resultTab/ResultTab.js
Labels: bug, frontend, feature

#35 Feature/#24 탭버튼 css
  package.json
  public/index.html
  src/App.js
  src/components/base/AuthCallback.js
  src/components/base/Header.js
  src/components/base/TabButton.js
  src/components/lostPostTab/LostPost.js
  src/components/resultTab/MatchResult.js
  src/components/resultTab/NoPost.js
  src/components/resultTab/NoResult.js
  src/components/resultTab/RenderList.js
  src/components/resultTab/ResultTab.js
Labels: frontend

#36 Feature/#25
  src/App.js
  src/components/base/Header.js
  src/components/base/TabButton.js
  src/components/lostPostTab/ImageUpload.js
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
  tailwind.config.js
Labels: frontend, feature

#37 Feature/#34
  src/components/base/Header.js
  src/components/resultDetail/NoticeContent.js
  src/components/resultTab/ResultTab.js
Labels: frontend, feature

#39 Bugfix/#38 입력 폼 폴더 바깥으로 나가는 이슈
  src/App.js
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
Labels: bug, frontend

#43 redirect url 수정
  src/components/base/AuthCallback.js
  src/components/base/Header.js
  src/components/base/TabButton.js
Labels: frontend

#44 Bugfix/#42 redirectUrl 재수정
  src/components/base/AuthCallback.js
  src/components/base/Header.js
Labels: frontend

#41 Feature/#24 css 1차 완료
  src/App.js
  src/assets/Curious dog.json
  src/assets/Dissapointed dog.json
  src/assets/Waiting dog.json
  src/assets/멍타주 로고(4).png
  src/components/base/AuthCallback.js
  src/components/base/Header.js
  src/components/base/TabButton.js
  src/components/base/Waiting.js
  src/components/lostPostTab/ImageUpload.js
  src/components/lostPostTab/LostPost.js
  src/components/resultDetail/NoticeContent.js
  src/components/resultTab/MatchResult.js
  src/components/resultTab/NoPost.js
  src/components/resultTab/NoResult.js
  src/components/resultTab/RenderList.js
  src/components/resultTab/ResultTab.js
  src/index.css
  src/pages/Auth.js
  src/pages/Home.js
  src/pages/MatchResult.js
  tailwind.config.js
Labels: frontend

#47 client instance CD를 위한 yml 작성
  .github/workflows/client.yml
Labels: frontend, feature

#48 Feature/#45 탭 뜨는 현상 수정
  src/App.js
  src/components/base/AuthCallback.js
  src/components/base/Header.js
  src/components/base/TabButton.js
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
  src/components/resultTab/NoPost.js
  src/components/resultTab/RenderList.js
  src/components/resultTab/ResultTab.js
  src/index.css
Labels: bug, frontend

#50 Feature/#30 분실 등록 결과 확인 및 삭제 폼 제작
  src/components/lostPostTab/IsImageUpload.js
  src/components/lostPostTab/IsLostForm.js
  src/components/lostPostTab/LostPost.js
Labels: frontend, feature

#52 Bugfix/#51
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
Labels: bug, frontend

#54 Feature/#45 custom alert
  package-lock.json
  package.json
  public/favicon.png
  public/favicon.svg
  public/index.html
  src/App.js
  src/components/base/Alert.js
  src/components/base/AuthCallback.js
  src/components/base/Header.js
  src/components/lostPostTab/ImageUpload.js
  src/components/lostPostTab/IsLostForm.js
  src/components/lostPostTab/LostForm.js
  src/components/lostPostTab/LostPost.js
  src/components/resultDetail/NoticeContent.js
  src/components/resultTab/NoResult.js
  src/components/resultTab/ResultTab.js
  yarn.lock
Labels: frontend

#57 로그아웃 해도 등록된 실종 신고는 그대로 보이는 이슈
  src/components/base/Header.js
Labels: bug, frontend

#60 Bugfix/#58
  .github/workflows/client.yml
Labels: bug

#59 Feature/#53 더보기 버튼 구현
  src/components/resultTab/MatchResult.js
  src/components/resultTab/RenderList.js
  src/components/resultTab/ResultTab.js
Labels: frontend, feature

#62 Feature/#45 custom alert 로그인 하지 않고 등록할때 alert
  src/components/lostPostTab/LostForm.js
Labels: bug, frontend

#63 삭제 api 연결
  src/components/lostPostTab/IsLostForm.js
Labels: feature

#64 Feature/#61 긴급 버그 수정
  src/components/lostPostTab/LostPost.js
  src/components/resultDetail/NoticeContent.js
  src/components/resultTab/MatchResult.js
Labels: bug, frontend

#65 Feature/#40 등록 페이지 라디오 버튼
  src/components/lostPostTab/IsLostForm.js
  src/components/lostPostTab/LostForm.js
Labels: frontend, feature
